
--1st
SELECT E.NAME,B.BONUS
FROM BONUS B
RIGHT JOIN EMPLOYEE E
ON E.EMPID=B.EMPID
WHERE B.BONUS<1000 OR B.BONUS IS NULL;


2nd
SELECT E.NAME,B.BONUS
FROM BONUS B
RIGHT JOIN EMPLOYEE E
ON E.EMPID=B.EMPID
WHERE IFNULL(B.BONUS,0)<1000;
-- WHERE B.BONUS<1000 OR B.BONUS IS NULL;
